// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_push_cube__friends_of_all = "CgkIweXpr4kQEAIQCQ"; // <GPGSID>
        public const string leaderboard_total_undo = "CgkIweXpr4kQEAIQBA"; // <GPGSID>
        public const string achievement_weclome_to_hobook_games = "CgkIweXpr4kQEAIQDA"; // <GPGSID>
        public const string achievement_push_cube_legend = "CgkIweXpr4kQEAIQCg"; // <GPGSID>
        public const string leaderboard_total_retries = "CgkIweXpr4kQEAIQBQ"; // <GPGSID>
        public const string achievement_push_cube_master = "CgkIweXpr4kQEAIQBw"; // <GPGSID>
        public const string achievement_welcome_to_push_cube = "CgkIweXpr4kQEAIQAQ"; // <GPGSID>
        public const string achievement_push_cube_expert = "CgkIweXpr4kQEAIQCA"; // <GPGSID>
        public const string achievement_push_cube__challenger = "CgkIweXpr4kQEAIQCw"; // <GPGSID>
        public const string leaderboard_clear_minimum_number_of_moves = "CgkIweXpr4kQEAIQAw"; // <GPGSID>
        public const string leaderboard_total_play_time = "CgkIweXpr4kQEAIQBg"; // <GPGSID>
        public const string leaderboard_current_stage = "CgkIweXpr4kQEAIQAg"; // <GPGSID>

}

